# https://travis-ci.org/diyan/assimilator
language: go
dist: trusty
# Define 'sudo: false' to run on container-based workers
sudo: false
cache:
  directories:
    - $HOME/.glide/cache
go:
  - 1.5.x
  - 1.8.x
  - master
env:
  - GOOS=linux GOARCH=amd64
  - GOOS=linux GOARCH=386
  - GOOS=linux GOARCH=arm
  - GOOS=darwin GOARCH=amd64
  - GOOS=darwin GOARCH=386
  - GOOS=darwin GOARCH=arm
  - GOOS=windows GOARCH=amd64
  - GOOS=windows GOARCH=386
  - GOOS=freebsd GOARCH=amd64
  - GOOS=freebsd GOARCH=386
  - GOOS=freebsd GOARCH=arm
services:
  - postgresql
before_install:
  - if go version | grep --quiet go1.5; then export GO15VENDOREXPERIMENT=1; fi
  - go get github.com/Masterminds/glide
  - go get github.com/onsi/ginkgo/ginkgo
install:
  - make get-go-deps
script:
  - make build-go
  - make test-go
#after_success:
#  - coveralls
